### ISSUE TITLE
When you export files to .afs, all files are deleted.

### ISSUE THREAD

**Issue by 11mw** [Exormeter/12Riven_ScriptEditor#1]
I can hardly help with the translation from Japanese, but I was interested to try this script.

I pulled out all the files ".CMD" from "SCENE00.afs" using KidTools and added them to the folders for "JP" and "ENG".  I change any one character, save the changes in the "save current file" option, and click on export to SCENE00 . But suddenly the size of this file is reduced to 2 kb, and accordingly, when trying to start a new game, 12Riven gives an error. Looking through the KidTools file Scene00, it finds nothing.

What do I need to do for the script to export files to Scene00.afs normally ? If anything, I run the application through the Debug folder.

My script window:
![image](https://user-images.githubusercontent.com/79114827/107998566-3cad3b80-7007-11eb-8d29-7999f5ae1e4d.png)

Kid Tools window after export (I specially pulled the Scene00.afs file into the script folder so that I could then throw it back into the 12Riven files)
![image](https://user-images.githubusercontent.com/79114827/107998804-b5ac9300-7007-11eb-945c-cf406055fae6.png)

**Comment by Exormeter** [comment]
Hi, I am currently working on a translationwith an translator, I just like to open source my tools ;)
Anyway, you are missing the list file that is basiclly a list of all CMDs inside the SCENE00.afs. You can get the list by extracting it with the Animed tool that can extract many different VS script files.
