### ISSUE TITLE
Nepi.BIN won't open in the editor

### ISSUE THREAD

**Issue by sorendipitous** [Exormeter/12Riven_ScriptEditor#4]
I assume this is a regular script file serving a similar purpose to Repi.BIN, but it's missing from the editor list view despite being in the list file and associated folder:
![image](https://user-images.githubusercontent.com/12383421/173254977-3a5aab1b-2cdf-41a7-931e-e59506727d32.png)

**Comment by Exormeter** [comment]
You are right, will address it
