### ISSUE TITLE
Can i Continue your project if you gave up on it? 

### ISSUE THREAD

**Issue by dorster** [Exormeter/12Riven_ScriptEditor#5]
And did you bypass the memory limit? im interested in translating it , i allready started but hit the Ca11b.bin roadblock...

**Comment by Exormeter** [comment]
Hi, I just started working on it again. I made progress in splitting these file in that I was able to jump to a different scene by splicing a goto command into the script. I need a bit more time to test what happens when a scene is splitt, but I think it should be possible

**Comment by dorster** [comment]
How far have you translated ? , i found a way some time ago and iv translated a few hours

**Comment by Exormeter** [comment]
I don't speak japanease and only developed it so others can use the tool to translate it. How did you bypass the limit? As far as I reverse engineered the engine it will only load 64kb chunks so a split is needed AFAIK

**Comment by Exormeter** [comment]
Oh also, to answer your question, it's not abandoned but if you want to contribute, feel free. It's the reason why this is open source.

**Comment by dorster** [comment]
I didn't bypass it xD .. I just Shortened my script, Shortened erm.. Some Sentences and "Details they give"[Only on Ca11b] I guess. It was only helpful on Ca11b Since i didn't really need to on the others i translated, Im pretty sure ill hit a roadblock again at Rb07 Since it is already 64kb  Your next version of the tool will allow me to bypass it Which is amazing Can't wait!,Btw how's it goin? ,Oh and another thing Have you figured out a way to change the text in the menus? Like options.. load save ect i wanna translate it so people would be able to understand

**Comment by Exormeter** [comment]
Yes, I know how to change the text in the menus and the other strings, but it’s currently not a priority as long as there is not a translation of the scripts. If a translator comes to me with a complete translation we can talk about the menu and the rest.

My approach is to split the longer scripts into two.

**Comment by dorster** [comment]
So will you make the splitting function Public once you are done with it ?

**Comment by Exormeter** [comment]
Yes, but it will take some time till I figure everything out.

**Comment by Exormeter** [comment]
Splitting is now supported
