### ISSUE TITLE
japanese Appears as blocks

### ISSUE THREAD

**Issue by dorster** [Exormeter/12Riven_ScriptEditor#7]
My locale and everything else is set up, version 0.01 works normally, but the new ver makes japanese chars appear as blocks{missing}

**Comment by dorster** [comment]
Ok so i checked again and apparently Japanese characters appear as normal when i type now, but all my scripts from 0.01 appear as blocks x(

**Comment by Exormeter** [comment]
Oops, I guess I have forgotten to change the text encoding back to Shift-Js. I use the Chinese version for reverse engineering, so the encoding us currently Big5.

will fix this shortly

**Comment by Exormeter** [comment]
Should be fixed now

**Comment by dorster** [comment]
You are awesome

**Comment by Exormeter** [comment]
Thanks, if you have other issues, please let me know. The testing I have done is limited so your experience is valuable.
